export function now() {
  // Lấy ngày tháng hiện tại
  const currentDate = new Date();

  // Lấy thông tin ngày, tháng, năm
  const year = currentDate.getFullYear();
  const month = String(currentDate.getMonth() + 1).padStart(2, "0"); // Tháng bắt đầu từ 0, sử dụng padStart để thêm số 0 phía trước nếu cần
  const day = String(currentDate.getDate()).padStart(2, "0");

  // Lấy thông tin giờ, phút, giây
  const hours = String(currentDate.getHours()).padStart(2, "0");
  const minutes = String(currentDate.getMinutes()).padStart(2, "0");
  const seconds = String(currentDate.getSeconds()).padStart(2, "0");

  // Định dạng theo định dạng DATETIME của SQL
  const formattedDateTime = `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
  return formattedDateTime;
}
export function formatCurrency(number: number) {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
  }).format(Math.round(number / 1000) * 1000);
}
export const districts = [
  {
    code: "164",
    name: "Thành phố Thái Nguyên",
    province: "Tỉnh Thái Nguyên",
  },
  {
    code: "171",
    name: "Huyện Đại Từ",
    province: "Tỉnh Thái Nguyên",
  },
  {
    code: "167",
    name: "Huyện Định Hóa",
    province: "Tỉnh Thái Nguyên",
  },
  {
    code: "169",
    name: "Huyện Đồng Hỷ",
    province: "Tỉnh Thái Nguyên",
  },
  {
    code: "173",
    name: "Huyện Phú Bình",
    province: "Tỉnh Thái Nguyên",
  },
  {
    code: "168",
    name: "Huyện Phú Lương",
    province: "Tỉnh Thái Nguyên",
  },
  {
    code: "170",
    name: "Huyện Võ Nhai",
    province: "Tỉnh Thái Nguyên",
  },
  {
    code: "172",
    name: "Thành phố Phổ Yên",
    province: "Tỉnh Thái Nguyên",
  },
  {
    code: "165",
    name: "Thành phố Sông Công",
    province: "Tỉnh Thái Nguyên",
  },
];
export function getDistrictById(id: string) {
  return districts.find((dt) => dt.code == id);
}
export function getWardById(id: string) {
  const districts = [
    {
      code: "05467",
      name: "Phường Cam Giá",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05659",
      name: "Phường Chùa Hang",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05710",
      name: "Phường Đồng Bẩm",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05458",
      name: "Phường Đồng Quang",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05461",
      name: "Phường Gia Sàng",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05440",
      name: "Phường Hoàng Văn Thụ",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05473",
      name: "Phường Hương Sơn",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05449",
      name: "Phường Phan Đình Phùng",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05470",
      name: "Phường Phú Xá",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05431",
      name: "Phường Quán Triều",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05446",
      name: "Phường Quang Trung",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05434",
      name: "Phường Quang Vinh",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05464",
      name: "Phường Tân Lập",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05482",
      name: "Phường Tân Long",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05479",
      name: "Phường Tân Thành",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05452",
      name: "Phường Tân Thịnh",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05455",
      name: "Phường Thịnh Đán",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05500",
      name: "Phường Tích Lương",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05476",
      name: "Phường Trung Thành",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05443",
      name: "Phường Trưng Vương",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05437",
      name: "Phường Túc Duyên",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05695",
      name: "Xã Cao Ngạn",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05914",
      name: "Xã Đồng Liên",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05713",
      name: "Xã Huống Thượng",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05701",
      name: "Xã Linh Sơn",
      district: "Thành phố Thái Nguyên\t",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05485",
      name: "Xã Phúc Hà",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05494",
      name: "Xã Phúc Trìu",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05488",
      name: "Xã Phúc Xuân",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05491",
      name: "Xã Quyết Thắng",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05653",
      name: "Xã Sơn Cẩm",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05503",
      name: "Xã Tân Cương",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05497",
      name: "Xã Thịnh Đức",
      district: "Thành phố Thái Nguyên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05528",
      name: "Phường Bách Quang",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05515",
      name: "Phường Cải Đan",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05509",
      name: "Phường Châu Sơn",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05506",
      name: "Phường Lương Sơn",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05512",
      name: "Phường Mỏ Chè",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05521",
      name: "Phường Phố Cò",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05518",
      name: "Phường Thắng Lợi",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05533",
      name: "Xã Bá Xuyên",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05530",
      name: "Xã Bình Sơn",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05527",
      name: "Xã Tân Quang",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05524",
      name: "Xã Vinh Sơn",
      district: "Thành phố Sông Công",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05536",
      name: "Thị trấn Chợ Chu",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05569",
      name: "Xã Bảo Cường",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05554",
      name: "Xã Bảo Linh",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05605",
      name: "Xã Bình Thành",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05587",
      name: "Xã Bình Yên",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05596",
      name: "Xã Bộc Nhiêu",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05590",
      name: "Xã Điềm Mặc",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05575",
      name: "Xã Định Biên",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05572",
      name: "Xã Đồng Thịnh",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05551",
      name: "Xã Kim Phượng",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05557",
      name: "Xã Kim Sơn",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05542",
      name: "Xã Lam Vỹ",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05539",
      name: "Xã Linh Thông",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05602",
      name: "Xã Phú Đình",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05593",
      name: "Xã Phú Tiến",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05560",
      name: "Xã Phúc Chu",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05566",
      name: "Xã Phượng Tiến",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05545",
      name: "Xã Quy Kỳ",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05599",
      name: "Xã Sơn Phú",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05563",
      name: "Xã Tân Dương",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05548",
      name: "Xã Tân Thịnh",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05578",
      name: "Xã Thanh Định",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05581",
      name: "Xã Trung Hội",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05584",
      name: "Xã Trung Lương",
      district: "Huyện Định Hóa",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05611",
      name: "Thị trấn Đu",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05608",
      name: "Thị trấn Giang Tiên",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05650",
      name: "Xã Cổ Lũng",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05629",
      name: "Xã Động Đạt",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05638",
      name: "Xã Hợp Thành",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05626",
      name: "Xã Ôn Lương",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05644",
      name: "Xã Phấn Mễ",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05635",
      name: "Xã Phú Đô",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05632",
      name: "Xã Phủ Lý",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05641",
      name: "Xã Tức Tranh",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05647",
      name: "Xã Vô Tranh",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05620",
      name: "Xã Yên Đổ",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05623",
      name: "Xã Yên Lạc",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05614",
      name: "Xã Yên Ninh",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05617",
      name: "Xã Yên Trạch",
      district: "Huyện Phú Lương",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05716",
      name: "Thị trấn Đình Cả",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05758",
      name: "Xã Bình Long",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05737",
      name: "Xã Cúc Đường",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05755",
      name: "Xã Dân Tiến",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05740",
      name: "Xã La Hiên",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05743",
      name: "Xã Lâu Thượng",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05752",
      name: "Xã Liên Minh",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05722",
      name: "Xã Nghinh Tường",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05734",
      name: "Xã Phú Thượng",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05749",
      name: "Xã Phương Giao",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05719",
      name: "Xã Sảng Mộc",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05725",
      name: "Xã Thần Xa",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05731",
      name: "Xã Thượng Nung",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05746",
      name: "Xã Tràng Xá",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05728",
      name: "Xã Vũ Chấn",
      district: "Huyện Võ Nhai",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05761",
      name: "Thị trấn Hùng Sơn",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05764",
      name: "Thị trấn Quân Chu",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05824",
      name: "Xã An Khánh",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05800",
      name: "Xã Bản Ngoại",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05830",
      name: "Xã Bình Thuận",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05848",
      name: "Xã Cát Nê",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05809",
      name: "Xã Cù Vân",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05776",
      name: "Xã Đức Lương",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05812",
      name: "Xã Hà Thượng",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05818",
      name: "Xã Hoàng Nông",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05821",
      name: "Xã Khôi Kỳ",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05845",
      name: "Xã Ký Phú",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05815",
      name: "Xã La Bằng",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05833",
      name: "Xã Lục Ba",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05770",
      name: "Xã Minh Tiến",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05836",
      name: "Xã Mỹ Yên",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05782",
      name: "Xã Na Mao",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05779",
      name: "Xã Phú Cường",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05785",
      name: "Xã Phú Lạc",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05791",
      name: "Xã Phú Thịnh",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05797",
      name: "Xã Phú Xuyên",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05794",
      name: "Xã Phục Linh",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05767",
      name: "Xã Phúc Lương",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05851",
      name: "Xã Quân Chu",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05788",
      name: "Xã Tân Linh",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05827",
      name: "Xã Tân Thái",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05803",
      name: "Xã Tiên Hội",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05839",
      name: "Xã Vạn Thọ",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05842",
      name: "Xã Văn Yên",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05773",
      name: "Xã Yên Lãng",
      district: "Huyện Đại Từ",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05860",
      name: "Phường Ba Hàng",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05857",
      name: "Phường Bắc Sơn",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05854",
      name: "Phường Bãi Bông",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05878",
      name: "Phường Đồng Tiến",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05875",
      name: "Xã Đắc Sơn",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05896",
      name: "Xã Đông Cao",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05869",
      name: "Xã Hồng Tiến",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05872",
      name: "Xã Minh Đức",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05890",
      name: "Xã Nam Tiến",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05863",
      name: "Xã Phúc Tân",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05866",
      name: "Xã Phúc Thuận",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05893",
      name: "Xã Tân Hương",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05902",
      name: "Xã Tân Phú",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05881",
      name: "Xã Thành Công",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05905",
      name: "Xã Thuận Thành",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05884",
      name: "Xã Tiên Phong",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05899",
      name: "Xã Trung Thành",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05887",
      name: "Xã Vạn Phái",
      district: "Thành phố Phổ Yên",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05908",
      name: "Thị trấn Hương Sơn",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05911",
      name: "Xã Bàn Đạt",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05929",
      name: "Xã Bảo Lý",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05965",
      name: "Xã Dương Thành",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05926",
      name: "Xã Đào Xá",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05941",
      name: "Xã Điềm Thụy",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05968",
      name: "Xã Hà Châu",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05959",
      name: "Xã Kha Sơn",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05953",
      name: "Xã Lương Phú",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05956",
      name: "Xã Nga My",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05938",
      name: "Xã Nhã Lộng",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05947",
      name: "Xã Tân Đức",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05935",
      name: "Xã Tân Hòa",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05917",
      name: "Xã Tân Khánh",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05920",
      name: "Xã Tân Kim",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05923",
      name: "Xã Tân Thành",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05962",
      name: "Xã Thanh Ninh",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05932",
      name: "Xã Thượng Đình",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05950",
      name: "Xã Úc Kỳ",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
    {
      code: "05944",
      name: "Xã Xuân Phương",
      district: "Huyện Phú Bình",
      province: "Tỉnh Thái Nguyên",
    },
  ];
  return districts.find((dt) => dt.code == id);
}
